#!/usr/bin/env bash
# install.sh: wire this dotfiles repo into Claude Code and Codex on this machine.
# Safe by design: backs up any existing real file to <file>.bak.<timestamp> before
# writing, never deletes your data, and is re-runnable. Handles paths with spaces.
set -euo pipefail

AGENTS_HOME="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
STAMP="$(date +%Y%m%d-%H%M%S)"
MARKER="GENERATED by ~/.agents"

echo "Installing from $AGENTS_HOME"
if [ "$AGENTS_HOME" != "$HOME/.agents" ]; then
  echo "note: repo is not at ~/.agents. The /scaffold command expects ~/.agents/scaffold.sh;"
  echo "      clone to ~/.agents or edit that path in commands/scaffold.md."
fi
echo

mkdir -p "$HOME/.claude/commands"

# CLAUDE.md and Codex AGENTS.md are generated by sync.sh. Back up a pre-existing USER
# file (one without our marker) once; our own generated file is safe to overwrite.
claude_md="$HOME/.claude/CLAUDE.md"
if [ -f "$claude_md" ] && ! grep -qF "$MARKER" "$claude_md" 2>/dev/null; then
  mv "$claude_md" "$claude_md.bak.$STAMP"
  echo "backed up $claude_md -> $claude_md.bak.$STAMP"
fi

codex_md="$HOME/.codex/AGENTS.md"
if [ -f "$codex_md" ] && ! grep -qF "$MARKER" "$codex_md" 2>/dev/null; then
  mkdir -p "$HOME/.codex"
  mv "$codex_md" "$codex_md.bak.$STAMP"
  echo "backed up $codex_md -> $codex_md.bak.$STAMP"
fi

# skills: symlink the canonical folder so Claude Code auto-trigger sees them.
skills_link="$HOME/.claude/skills"
if [ -L "$skills_link" ]; then
  rm "$skills_link"
elif [ -e "$skills_link" ]; then
  mv "$skills_link" "$skills_link.bak.$STAMP"
  echo "backed up $skills_link -> $skills_link.bak.$STAMP"
fi
ln -s "$AGENTS_HOME/skills" "$skills_link"
echo "linked $skills_link -> $AGENTS_HOME/skills"

# global slash commands (e.g. /scaffold, /save, /resume): symlink per-file so edits in
# ~/.agents go live without a re-install (like skills). Per-file, not a dir symlink,
# because ~/.claude/commands may also hold commands from other sources.
for cmd in "$AGENTS_HOME"/commands/*.md; do
  [ -e "$cmd" ] || continue
  name="$(basename "$cmd")"
  dest="$HOME/.claude/commands/$name"
  if [ -L "$dest" ]; then
    rm "$dest"
  elif [ -e "$dest" ]; then
    mv "$dest" "$dest.bak.$STAMP"
    echo "backed up $dest -> $dest.bak.$STAMP"
  fi
  ln -s "$cmd" "$dest"
  echo "linked command /${name%.md}"
done
echo

# SessionEnd hook: append breadcrumbs to the vault. Wired with the args form so a
# space in the path is safe.
settings="$HOME/.claude/settings.json"
hook_path="$AGENTS_HOME/hooks/session-end.sh"
chmod +x "$hook_path" 2>/dev/null || true

if [ ! -f "$settings" ]; then
  cat > "$settings" <<EOF
{
  "hooks": {
    "SessionEnd": [
      { "hooks": [ { "type": "command", "command": "bash", "args": ["$hook_path"] } ] }
    ]
  }
}
EOF
  echo "wrote $settings (wired SessionEnd hook)"
elif command -v jq >/dev/null 2>&1; then
  cp "$settings" "$settings.bak.$STAMP"
  tmp="$(mktemp)"
  if jq --arg p "$hook_path" '
      .hooks = (.hooks // {})
      | .hooks.SessionEnd = (.hooks.SessionEnd // [])
      | if any(.hooks.SessionEnd[]?; (.hooks[]?.args[]?) == $p) then .
        else .hooks.SessionEnd += [ { "hooks": [ { "type": "command", "command": "bash", "args": [ $p ] } ] } ] end
    ' "$settings" > "$tmp" 2>/dev/null; then
    mv "$tmp" "$settings"
    echo "merged SessionEnd hook into $settings (backup: $settings.bak.$STAMP)"
  else
    rm -f "$tmp" "$settings.bak.$STAMP"
    echo "could not parse $settings; left it untouched. Add this under \"hooks\":"
    echo "  \"SessionEnd\": [ { \"hooks\": [ { \"type\": \"command\", \"command\": \"bash\", \"args\": [\"$hook_path\"] } ] } ]"
  fi
else
  echo "note: $settings exists and jq is not installed; not modifying it. Add under \"hooks\":"
  echo "  \"SessionEnd\": [ { \"hooks\": [ { \"type\": \"command\", \"command\": \"bash\", \"args\": [\"$hook_path\"] } ] } ]"
fi
echo

# Generate the global Claude + Codex files from canonical.
bash "$AGENTS_HOME/sync.sh"

echo
echo "Done."
echo "Manual step for Cursor: paste AGENTS.md + overlays/cursor.md into"
echo "  Cursor Settings > Rules > User Rules."
echo
echo "Any backups use the suffix .bak.$STAMP and were left in place."
