#!/usr/bin/env bash
# install.sh: wire this dotfiles repo into Claude Code on this machine.
# Safe by design: backs up any existing real file to <file>.bak.<timestamp> before
# writing, never deletes your data, and is re-runnable. Handles paths with spaces.
set -euo pipefail

AGENTS_HOME="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
STAMP="$(date +%Y%m%d-%H%M%S)"
MARKER="GENERATED by ~/.agents"

echo "Installing from $AGENTS_HOME"
if [ "$AGENTS_HOME" != "$HOME/.agents" ]; then
  echo "note: repo is not at ~/.agents. The /scaffold command expects ~/.agents/scaffold.sh;"
  echo "      clone to ~/.agents or edit that path in commands/scaffold.md."
fi
echo

mkdir -p "$HOME/.claude/commands"

# CLAUDE.md is generated by sync.sh. Back up a pre-existing USER file (one without
# our marker) once; our own generated file is safe to overwrite.
claude_md="$HOME/.claude/CLAUDE.md"
if [ -f "$claude_md" ] && ! grep -qF "$MARKER" "$claude_md" 2>/dev/null; then
  mv "$claude_md" "$claude_md.bak.$STAMP"
  echo "backed up $claude_md -> $claude_md.bak.$STAMP"
fi

# skills: symlink the canonical folder so Claude Code auto-trigger sees them.
skills_link="$HOME/.claude/skills"
if [ -L "$skills_link" ]; then
  rm "$skills_link"
elif [ -e "$skills_link" ]; then
  mv "$skills_link" "$skills_link.bak.$STAMP"
  echo "backed up $skills_link -> $skills_link.bak.$STAMP"
fi
ln -s "$AGENTS_HOME/skills" "$skills_link"
echo "linked $skills_link -> $AGENTS_HOME/skills"

# global slash commands (e.g. /scaffold, /save, /recall): symlink per-file so edits in
# ~/.agents go live without a re-install (like skills). Per-file, not a dir symlink,
# because ~/.claude/commands may also hold commands from other sources.
for cmd in "$AGENTS_HOME"/commands/*.md; do
  [ -e "$cmd" ] || continue
  name="$(basename "$cmd")"
  dest="$HOME/.claude/commands/$name"
  if [ -L "$dest" ]; then
    rm "$dest"
  elif [ -e "$dest" ]; then
    mv "$dest" "$dest.bak.$STAMP"
    echo "backed up $dest -> $dest.bak.$STAMP"
  fi
  ln -s "$cmd" "$dest"
  echo "linked command /${name%.md}"
done
echo

# Machine-wide git ignore: personal agent files must stay invisible in EVERY repo,
# including ones you don't own — the template .gitignore only lands in repos you
# scaffold, and editing someone else's .gitignore costs them a review. The pattern
# list is read from the template itself (templates/project/.gitignore), the single
# source — a pattern added there reaches both scaffolded repos and this seed.
gitignore_global="$(git config --get core.excludesfile 2>/dev/null || true)"
gitignore_global="${gitignore_global:-${XDG_CONFIG_HOME:-$HOME/.config}/git/ignore}"
gitignore_global="${gitignore_global/#\~/$HOME}"
mkdir -p "$(dirname "$gitignore_global")"
touch "$gitignore_global"
[ -s "$gitignore_global" ] && [ -n "$(tail -c1 "$gitignore_global")" ] && echo >> "$gitignore_global"
while IFS= read -r pat; do
  case "$pat" in ''|'#'*) continue ;; esac
  if ! grep -qxF "$pat" "$gitignore_global"; then
    printf '%s\n' "$pat" >> "$gitignore_global"
    echo "global git ignore += $pat ($gitignore_global)"
  fi
done < "$AGENTS_HOME/templates/project/.gitignore"
echo

# SessionEnd hook: append breadcrumbs to the vault. Wired with the args form so a
# space in the path is safe.
settings="$HOME/.claude/settings.json"
hook_path="$AGENTS_HOME/hooks/session-end.sh"
chmod +x "$hook_path" 2>/dev/null || true

if [ ! -f "$settings" ]; then
  cat > "$settings" <<EOF
{
  "hooks": {
    "SessionEnd": [
      { "hooks": [ { "type": "command", "command": "bash", "args": ["$hook_path"] } ] }
    ]
  }
}
EOF
  echo "wrote $settings (wired SessionEnd hook)"
elif command -v jq >/dev/null 2>&1; then
  if jq -e --arg p "$hook_path" 'any(.hooks.SessionEnd[]?; (.hooks[]?.args[]?) == $p)' \
      "$settings" >/dev/null 2>&1; then
    echo "SessionEnd hook already wired in $settings"
  else
    cp "$settings" "$settings.bak.$STAMP"
    tmp="$(mktemp)"
    if jq --arg p "$hook_path" '
        .hooks = (.hooks // {})
        | .hooks.SessionEnd = (.hooks.SessionEnd // [])
        | .hooks.SessionEnd += [ { "hooks": [ { "type": "command", "command": "bash", "args": [ $p ] } ] } ]
      ' "$settings" > "$tmp" 2>/dev/null; then
      mv "$tmp" "$settings"
      echo "merged SessionEnd hook into $settings (backup: $settings.bak.$STAMP)"
    else
      rm -f "$tmp" "$settings.bak.$STAMP"
      echo "could not parse $settings; left it untouched. Add this under \"hooks\":"
      echo "  \"SessionEnd\": [ { \"hooks\": [ { \"type\": \"command\", \"command\": \"bash\", \"args\": [\"$hook_path\"] } ] } ]"
    fi
  fi
else
  echo "note: $settings exists and jq is not installed; not modifying it. Add under \"hooks\":"
  echo "  \"SessionEnd\": [ { \"hooks\": [ { \"type\": \"command\", \"command\": \"bash\", \"args\": [\"$hook_path\"] } ] } ]"
fi
echo

# Daily vault backup: a launchd agent runs hooks/vault-daily.sh at 17:00 (commit +
# push ~/Vault to its private remote). launchd, not cron: a run missed while the
# laptop sleeps fires on the next wake; cron would skip it silently. The plist is
# generated, so overwriting it on re-install is safe.
chmod +x "$AGENTS_HOME/hooks/vault-daily.sh" 2>/dev/null || true
plist="$HOME/Library/LaunchAgents/com.agent-config.vault-daily.plist"
mkdir -p "$(dirname "$plist")"
cat > "$plist" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>com.agent-config.vault-daily</string>
  <key>ProgramArguments</key>
  <array>
    <string>/bin/bash</string>
    <string>$AGENTS_HOME/hooks/vault-daily.sh</string>
  </array>
  <key>StartCalendarInterval</key>
  <dict><key>Hour</key><integer>17</integer><key>Minute</key><integer>0</integer></dict>
</dict>
</plist>
EOF
launchctl bootout "gui/$(id -u)" "$plist" 2>/dev/null || true
if launchctl bootstrap "gui/$(id -u)" "$plist" 2>/dev/null; then
  echo "installed launchd agent com.agent-config.vault-daily (daily 17:00)"
else
  echo "note: could not load $plist via launchctl; load it by hand or run"
  echo "  bash $AGENTS_HOME/hooks/vault-daily.sh   from cron/manually instead."
fi
echo

# Keep the baked globals fresh: a post-commit hook in this repo re-runs sync.sh
# (idempotent and instant), so a committed rules edit can't silently go stale.
if hooksdir="$(git -C "$AGENTS_HOME" rev-parse --path-format=absolute --git-path hooks 2>/dev/null)"; then
  mkdir -p "$hooksdir"
  agents_hook="$hooksdir/post-commit"
  sync_line="bash \"$AGENTS_HOME\"/sync.sh >/dev/null && echo 'sync.sh: regenerated baked globals'"
  if [ -f "$agents_hook" ]; then
    if ! grep -q "sync.sh" "$agents_hook"; then
      [ -n "$(tail -c1 "$agents_hook")" ] && echo >> "$agents_hook"
      printf '%s\n' "$sync_line" >> "$agents_hook"
      echo "added sync line to existing $agents_hook"
    fi
  else
    printf '#!/usr/bin/env bash\n%s\n' "$sync_line" > "$agents_hook"
    echo "wrote $agents_hook (re-bakes globals on commit)"
  fi
  chmod +x "$agents_hook"
fi
echo

# Generate the global Claude file from canonical.
bash "$AGENTS_HOME/sync.sh"

echo
echo "Done."
echo "Manual step for Cursor: paste generated/cursor-user-rules.md into"
echo "  Cursor Settings > Rules > User Rules."
echo
echo "Any backups use the suffix .bak.$STAMP and were left in place."
