#!/usr/bin/env bash
# sync.sh: regenerate the global tool files from the canonical source.
# Both Claude and Codex globals are BAKED (concatenated), not imported, because
# @import is unreliable for home/absolute paths (and this home path has a space).
# Per-repo CLAUDE.md still uses the reliable relative @AGENTS.md import.
#
# Shared always-on rules from rules/ (currently just the pinned ponytail snapshot)
# are baked in between AGENTS.md and the tool overlay. Each global is built in a
# temp file next to its destination and renamed into place, so a failed run can
# never half-write one. `sync.sh --check` diffs instead of writing and exits
# nonzero on drift.
set -euo pipefail

AGENTS_HOME="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MARKER="<!-- GENERATED by ~/.agents (sync.sh). Edit AGENTS.md / overlays, not this file. -->"
CHECK=0
[ "${1:-}" = "--check" ] && CHECK=1

# every source must exist before anything is written
for f in AGENTS.md overlays/claude-code.md overlays/codex.md overlays/cursor.md; do
  [ -f "$AGENTS_HOME/$f" ] || { echo "error: missing $AGENTS_HOME/$f" >&2; exit 1; }
done

tmp=""
trap '[ -n "$tmp" ] && rm -f "$tmp"' EXIT

drift=0
bake() { # bake <overlay> <dest> <label>
  local overlay="$1" dest="$2" label="$3"
  mkdir -p "$(dirname "$dest")"
  tmp="$(mktemp "$(dirname "$dest")/.sync-tmp.XXXXXX")"
  {
    printf '%s\n\n' "$MARKER"
    cat "$AGENTS_HOME/AGENTS.md"
    if [ -f "$AGENTS_HOME/rules/ponytail.md" ]; then
      printf '\n---\n\n'
      cat "$AGENTS_HOME/rules/ponytail.md"
    fi
    printf '\n---\n\n'
    cat "$AGENTS_HOME/$overlay"
  } > "$tmp"
  if [ "$CHECK" -eq 1 ]; then
    if ! diff -q "$dest" "$tmp" >/dev/null 2>&1; then
      echo "stale: $label ($dest) — run ./sync.sh"
      drift=1
    fi
    rm -f "$tmp"
  else
    mv "$tmp" "$dest"
    echo "wrote $dest"
  fi
  tmp=""
}

bake overlays/claude-code.md "$HOME/.claude/CLAUDE.md" "Claude global"
bake overlays/codex.md "$HOME/.codex/AGENTS.md" "Codex global"
bake overlays/cursor.md "$AGENTS_HOME/generated/cursor-user-rules.md" "Cursor bundle"

if [ "$CHECK" -eq 1 ]; then
  [ "$drift" -eq 0 ] && echo "globals match canonical sources"
  exit "$drift"
fi

echo
echo "Cursor is manual: paste generated/cursor-user-rules.md into"
echo "Cursor Settings > Rules > User Rules (Cursor has no on-disk global file)."
