#!/usr/bin/env bash
# sync.sh: regenerate the global tool files from the canonical source.
# Both Claude and Codex globals are BAKED (concatenated), not imported, because
# @import is unreliable for home/absolute paths (and this home path has a space).
# Per-repo CLAUDE.md still uses the reliable relative @AGENTS.md import.
set -euo pipefail

AGENTS_HOME="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MARKER="<!-- GENERATED by ~/.agents (sync.sh). Edit AGENTS.md / overlays, not this file. -->"

# Claude global
mkdir -p "$HOME/.claude"
{
  printf '%s\n\n' "$MARKER"
  cat "$AGENTS_HOME/AGENTS.md"
  printf '\n---\n\n'
  cat "$AGENTS_HOME/overlays/claude.md"
} > "$HOME/.claude/CLAUDE.md"
echo "wrote $HOME/.claude/CLAUDE.md"

# Codex global
mkdir -p "$HOME/.codex"
{
  printf '%s\n\n' "$MARKER"
  cat "$AGENTS_HOME/AGENTS.md"
  printf '\n---\n\n'
  cat "$AGENTS_HOME/overlays/codex.md"
} > "$HOME/.codex/AGENTS.md"
echo "wrote $HOME/.codex/AGENTS.md"

echo
echo "Cursor is manual: paste AGENTS.md + overlays/cursor.md into"
echo "Cursor Settings > Rules > User Rules (Cursor has no on-disk global file)."
