#!/usr/bin/env bash
# sync.sh: regenerate the global Claude file from the canonical source.
# The global is BAKED (concatenated), not @imported — a choice re-affirmed on
# review 2026-08-26. The original rationale ("@import is unreliable for home
# paths", "this home path has a space") is dead: the CLI documents @~/ imports
# as supported, and this home path has no space. The live reason is Cowork
# desktop, which skips user-scope external imports (and a symlinked
# ~/.claude/CLAUDE.md entirely) — an import-based global would silently load
# nothing there, while a baked flat file works on every surface. The post-commit
# hook and `sync.sh --check` keep the bake from going stale.
# Per-repo CLAUDE.md still uses the relative @AGENTS.md import.
#
# Shared always-on rules from rules/ (currently just the pinned ponytail snapshot)
# are baked in between AGENTS.md and the tool overlay. Each global is built in a
# temp file next to its destination and renamed into place, so a failed run can
# never half-write one. `sync.sh --check` diffs instead of writing and exits
# nonzero on drift. A destination missing the GENERATED marker is treated as
# human-authored: interactive runs ask before overwriting, non-interactive runs
# (the post-commit hook) skip it with a warning.
set -euo pipefail

AGENTS_HOME="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MARKER="<!-- GENERATED by ~/.agents (sync.sh). Edit AGENTS.md / overlays, not this file. -->"
CHECK=0
[ "${1:-}" = "--check" ] && CHECK=1

# every source must exist before anything is written
for f in AGENTS.md overlays/claude-code.md; do
  [ -f "$AGENTS_HOME/$f" ] || { echo "error: missing $AGENTS_HOME/$f" >&2; exit 1; }
done

tmp=""
trap '[ -n "$tmp" ] && rm -f "$tmp"' EXIT

drift=0
skipped=0
bake() { # bake <overlay> <dest> <label>
  local overlay="$1" dest="$2" label="$3"
  mkdir -p "$(dirname "$dest")"
  tmp="$(mktemp "$(dirname "$dest")/.sync-tmp.XXXXXX")"
  {
    printf '%s\n\n' "$MARKER"
    cat "$AGENTS_HOME/AGENTS.md"
    if [ -f "$AGENTS_HOME/rules/ponytail.md" ]; then
      printf '\n---\n\n'
      cat "$AGENTS_HOME/rules/ponytail.md"
    fi
    printf '\n---\n\n'
    cat "$AGENTS_HOME/$overlay"
  } > "$tmp"
  if [ "$CHECK" -eq 1 ]; then
    if ! diff -q "$dest" "$tmp" >/dev/null 2>&1; then
      echo "stale: $label ($dest) — run ./sync.sh"
      drift=1
    fi
    rm -f "$tmp"
  else
    # human in the loop: a destination without the GENERATED marker is (or may
    # be) human-authored — ask before replacing it; never overwrite unprompted.
    if [ -f "$dest" ] && ! grep -qF "GENERATED by ~/.agents" "$dest"; then
      if [ -t 0 ]; then
        printf '%s exists without the GENERATED marker (human-authored?). Overwrite? [y/N] ' "$dest"
        read -r reply
        case "$reply" in
          [Yy]*) ;;
          *)
            echo "skipped $label — kept your $dest" >&2
            skipped=1
            rm -f "$tmp"; tmp=""
            return
            ;;
        esac
      else
        echo "warning: $dest lacks the GENERATED marker; not overwriting. Run ./sync.sh in a terminal to confirm." >&2
        skipped=1
        rm -f "$tmp"; tmp=""
        return
      fi
    fi
    # Safety copy before the overwrite: an append to the generated file (e.g. a
    # '#' user-memory save) keeps the marker, so the overwrite below is by
    # design — the copy makes a clobbered append recoverable instead of gone.
    if [ -f "$dest" ]; then cp "$dest" "$dest.pre-sync" 2>/dev/null || true; fi
    mv "$tmp" "$dest"
    echo "wrote $dest"
  fi
  tmp=""
}

bake overlays/claude-code.md "$HOME/.claude/CLAUDE.md" "Claude global"

if [ "$CHECK" -eq 1 ]; then
  [ "$drift" -eq 0 ] && echo "globals match canonical sources"
  exit "$drift"
fi

# A skipped bake exits nonzero so callers (the SessionStart self-heal) can see
# that the one unhealable state — a markerless destination — actually occurred,
# instead of reporting success over a heal that never happened.
exit "$skipped"
